name: tws.management
main: dev.kylejulian.tws.ManagementPlugin
author: JuHDude
version: 0.0.1
api-version: 1.15
database: true
softdepend: [TAB]
commands:
  afk:
    description: To go afk. Specify the exempt keyword and a Player name to prevent them from being kicked for inactivity.
    usage: |
      /<command> [exempt [add|remove|list] [player]]
      Example: /<command>
      Example: /<command> exempt add Player1
      Example: /<command> exempt remove Player1
permissions:
  tws.*:
    description: Gives access to all commands from the TWS plugin.
    children:
      tws.afk.exempt: true
  tws.afk.exempt:
    description: Gives access to add and remove players to the inactivity kick exempt list.