main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
database: true
softdepend: [TAB, LuckPerms]
commands:
  afk:
    description: To go afk. Specify the exempt keyword and a Player name to prevent them from being kicked for inactivity.
    usage: |
      /<command> [exempt [add|remove|list] [player]]
      Example: /<command>
      Example: /<command> exempt add Player1
      Example: /<command> exempt remove Player1
  hud:
    description: To enable or disable the HUD for showing coordinates and time
    usage: |
      /<command>
      Example: /<command>
  exe:
    description: To add a player to whitelist exempt list. Specify 'list' to display everyone in the list. Use the command again if you want to remove them from the exempt list
    usage: |
      /<command> [add|remove|list]
      Example: /<command> add Player1
      Example: /<command> remove Player1
      Example: /<command> list
    permission: tws.exempt
permissions:
  tws.*:
    description: Gives access to all commands from the TWS plugin.
    children:
      tws.afk.exempt: true
  tws.afk.exempt:
    description: Gives access to add and remove players to the inactivity kick exempt list.
  tws.exe.auto:
    description: A player with this permission node will not be removed from the whitelisted automatically