name: tws.management
main: tws.management.ManagementPlugin
author: KyleJ
version: 0.0.1
api-version: 1.14
database: true
commands:
  afk:
    description: To go afk. Specify the exempt keyword and a Player name to prevent them from being kicked for inactivity.
    usage: |
      /<command> [exempt [add|remove] [player]]
      Example: /<command>
      Example: /<command> exempt add Player1
      Example: /<command> exempt remove Player1