name: Release on tag

on:
  push:
    tags:
      - 'v*.*.*' # For v1.0, v0.1.0, etc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.3

    - name: Set up JDK 17
      uses: actions/setup-java@v3.11.0
      with:
        java-version: '17'
        distribution: 'microsoft'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.5.1
      with:
        gradle-version: 8.2
        arguments: build release

    - name: Find Release Asset Details
      id: export_asset_vars
      run: |
        echo "Version is ${GITHUB_REF_NAME}"
        asset=$(find ${{ github.workspace }}/build/libs -name TWSManagement\*)
        echo "::set-output name=ASSET_NAME::$asset"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          ${{ steps.export_asset_vars.outputs.ASSET_NAME }}
