name: Release on tag

on:
  push:
    tags:
      - 'v*.*.*' # For v1.0, v0.1.0, etc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.3.1
        arguments: build -Pver=${GITHUB_REF_NAME} release

    - name: Find Release Asset Details
      id: export_asset_vars
      run: |
        asset=$(find ${{ github.workspace }}/build/libs -name TWSManagement\*)
        echo "::set-output name=ASSET_NAME::$asset"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          ${{ steps.export_asset_vars.outputs.ASSET_NAME }}
